transcript off
onbreak {quit -force}
onerror {quit -force}
transcript on

vlib work
vlib activehdl/xilinx_vip
vlib activehdl/xpm
vlib activehdl/lib_pkg_v1_0_3
vlib activehdl/fifo_generator_v13_2_9
vlib activehdl/lib_fifo_v1_0_18
vlib activehdl/lib_srl_fifo_v1_0_3
vlib activehdl/lib_cdc_v1_0_2
vlib activehdl/axi_datamover_v5_1_31
vlib activehdl/axi_sg_v4_1_17
vlib activehdl/axi_dma_v7_1_30
vlib activehdl/xil_defaultlib
vlib activehdl/xlconstant_v1_1_8
vlib activehdl/proc_sys_reset_v5_0_14
vlib activehdl/smartconnect_v1_0
vlib activehdl/axi_infrastructure_v1_1_0
vlib activehdl/axi_register_slice_v2_1_29
vlib activehdl/axi_vip_v1_1_15
vlib activehdl/processing_system7_vip_v1_0_17
vlib activehdl/xlconcat_v2_1_5
vlib activehdl/generic_baseblocks_v2_1_1
vlib activehdl/axi_data_fifo_v2_1_28
vlib activehdl/axi_crossbar_v2_1_30
vlib activehdl/axi_protocol_converter_v2_1_29

vmap xilinx_vip activehdl/xilinx_vip
vmap xpm activehdl/xpm
vmap lib_pkg_v1_0_3 activehdl/lib_pkg_v1_0_3
vmap fifo_generator_v13_2_9 activehdl/fifo_generator_v13_2_9
vmap lib_fifo_v1_0_18 activehdl/lib_fifo_v1_0_18
vmap lib_srl_fifo_v1_0_3 activehdl/lib_srl_fifo_v1_0_3
vmap lib_cdc_v1_0_2 activehdl/lib_cdc_v1_0_2
vmap axi_datamover_v5_1_31 activehdl/axi_datamover_v5_1_31
vmap axi_sg_v4_1_17 activehdl/axi_sg_v4_1_17
vmap axi_dma_v7_1_30 activehdl/axi_dma_v7_1_30
vmap xil_defaultlib activehdl/xil_defaultlib
vmap xlconstant_v1_1_8 activehdl/xlconstant_v1_1_8
vmap proc_sys_reset_v5_0_14 activehdl/proc_sys_reset_v5_0_14
vmap smartconnect_v1_0 activehdl/smartconnect_v1_0
vmap axi_infrastructure_v1_1_0 activehdl/axi_infrastructure_v1_1_0
vmap axi_register_slice_v2_1_29 activehdl/axi_register_slice_v2_1_29
vmap axi_vip_v1_1_15 activehdl/axi_vip_v1_1_15
vmap processing_system7_vip_v1_0_17 activehdl/processing_system7_vip_v1_0_17
vmap xlconcat_v2_1_5 activehdl/xlconcat_v2_1_5
vmap generic_baseblocks_v2_1_1 activehdl/generic_baseblocks_v2_1_1
vmap axi_data_fifo_v2_1_28 activehdl/axi_data_fifo_v2_1_28
vmap axi_crossbar_v2_1_30 activehdl/axi_crossbar_v2_1_30
vmap axi_protocol_converter_v2_1_29 activehdl/axi_protocol_converter_v2_1_29

vlog -work xilinx_vip  -sv2k12 "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm  -sv2k12 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93  \
"C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_VCOMP.vhd" \

vcom -work lib_pkg_v1_0_3 -93  \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/56d9/hdl/lib_pkg_v1_0_rfs.vhd" \

vlog -work fifo_generator_v13_2_9  -v2k5 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ac72/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_2_9 -93  \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ac72/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -work fifo_generator_v13_2_9  -v2k5 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ac72/hdl/fifo_generator_v13_2_rfs.v" \

vcom -work lib_fifo_v1_0_18 -93  \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/1531/hdl/lib_fifo_v1_0_rfs.vhd" \

vcom -work lib_srl_fifo_v1_0_3 -93  \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/02c4/hdl/lib_srl_fifo_v1_0_rfs.vhd" \

vcom -work lib_cdc_v1_0_2 -93  \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work axi_datamover_v5_1_31 -93  \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/d786/hdl/axi_datamover_v5_1_vh_rfs.vhd" \

vcom -work axi_sg_v4_1_17 -93  \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/1b4d/hdl/axi_sg_v4_1_rfs.vhd" \

vcom -work axi_dma_v7_1_30 -93  \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ddec/hdl/axi_dma_v7_1_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  \
"../../../bd/Arty_Z7/ip/Arty_Z7_axi_dma_0_0/sim/Arty_Z7_axi_dma_0_0.vhd" \

vlog -work xlconstant_v1_1_8  -v2k5 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/d390/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_0/sim/bd_f994_one_0.v" \

vcom -work proc_sys_reset_v5_0_14 -93  \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/408c/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  \
"../../../bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_1/sim/bd_f994_psr_aclk_0.vhd" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/c6b2/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_2/sim/bd_f994_s00mmu_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/abb8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_3/sim/bd_f994_s00tr_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/7827/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_4/sim/bd_f994_s00sic_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/79ce/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_5/sim/bd_f994_s00a2s_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_6/sim/bd_f994_sarn_0.sv" \
"../../../bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_7/sim/bd_f994_srn_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ebf7/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_8/sim/bd_f994_m00s2a_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6eea/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_9/sim/bd_f994_m00e_0.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/sim/bd_f994.v" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/bd53/hdl/sc_switchboard_v1_0_vl_rfs.sv" \

vlog -work axi_infrastructure_v1_1_0  -v2k5 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_29  -v2k5 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ff9f/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work axi_vip_v1_1_15  -sv2k12 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/5753/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/sim/Arty_Z7_axi_smc_0.v" \

vcom -work xil_defaultlib -93  \
"../../../bd/Arty_Z7/ip/Arty_Z7_proc_sys_reset_0_0/sim/Arty_Z7_proc_sys_reset_0_0.vhd" \

vlog -work processing_system7_vip_v1_0_17  -sv2k12 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../bd/Arty_Z7/ip/Arty_Z7_processing_system7_0_1/sim/Arty_Z7_processing_system7_0_1.v" \

vlog -work xlconcat_v2_1_5  -v2k5 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/147b/hdl/xlconcat_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../bd/Arty_Z7/ip/Arty_Z7_xlconcat_0_0/sim/Arty_Z7_xlconcat_0_0.v" \
"../../../bd/Arty_Z7/ipshared/62cb/rtl/Layer_1.v" \
"../../../bd/Arty_Z7/ipshared/62cb/rtl/Layer_2.v" \
"../../../bd/Arty_Z7/ipshared/62cb/rtl/Layer_3.v" \
"../../../bd/Arty_Z7/ipshared/62cb/rtl/Sig_ROM.v" \
"../../../bd/Arty_Z7/ipshared/62cb/rtl/Weight_Memory.v" \
"../../../bd/Arty_Z7/ipshared/62cb/rtl/axi_lite_wrapper.v" \
"../../../bd/Arty_Z7/ipshared/62cb/rtl/maxFinder.v" \
"../../../bd/Arty_Z7/ipshared/62cb/rtl/neuron.v" \
"../../../bd/Arty_Z7/ipshared/62cb/rtl/relu.v" \
"../../../bd/Arty_Z7/ipshared/62cb/rtl/zynet.v" \
"../../../bd/Arty_Z7/ip/Arty_Z7_zyNet_0_0/sim/Arty_Z7_zyNet_0_0.v" \

vlog -work generic_baseblocks_v2_1_1  -v2k5 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/10ab/hdl/generic_baseblocks_v2_1_vl_rfs.v" \

vlog -work axi_data_fifo_v2_1_28  -v2k5 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/279e/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_crossbar_v2_1_30  -v2k5 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/fb47/hdl/axi_crossbar_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../bd/Arty_Z7/ip/Arty_Z7_xbar_0/sim/Arty_Z7_xbar_0.v" \

vlog -work axi_protocol_converter_v2_1_29  -v2k5 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/a63f/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/f0b6/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/35de/hdl/verilog" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/ec67/hdl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/6b2b/hdl" "+incdir+../../../bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+../../../../CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ipshared/62cb/rtl" "+incdir+C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l lib_pkg_v1_0_3 -l fifo_generator_v13_2_9 -l lib_fifo_v1_0_18 -l lib_srl_fifo_v1_0_3 -l lib_cdc_v1_0_2 -l axi_datamover_v5_1_31 -l axi_sg_v4_1_17 -l axi_dma_v7_1_30 -l xil_defaultlib -l xlconstant_v1_1_8 -l proc_sys_reset_v5_0_14 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l processing_system7_vip_v1_0_17 -l xlconcat_v2_1_5 -l generic_baseblocks_v2_1_1 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 \
"../../../bd/Arty_Z7/ip/Arty_Z7_auto_pc_0/sim/Arty_Z7_auto_pc_0.v" \
"../../../bd/Arty_Z7/sim/Arty_Z7.v" \

vlog -work xil_defaultlib \
"glbl.v"

