# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.srcs/sources_1/bd/Arty_Z7/ip/Arty_Z7_processing_system7_0_1/Arty_Z7_processing_system7_0_1.xci
# IP: The module: 'Arty_Z7_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_processing_system7_0_1/Arty_Z7_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Arty_Z7_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.srcs/sources_1/bd/Arty_Z7/ip/Arty_Z7_processing_system7_0_1/Arty_Z7_processing_system7_0_1.xci
# IP: The module: 'Arty_Z7_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_processing_system7_0_1/Arty_Z7_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Arty_Z7_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
