# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.srcs/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/Arty_Z7_axi_smc_0.xci
# IP: The module: 'Arty_Z7_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/bd_f994.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_0/bd_f994_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_1/bd_f994_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_2/bd_f994_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_3/bd_f994_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_4/bd_f994_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_5/bd_f994_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_6/bd_f994_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_7/bd_f994_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_8/bd_f994_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_9/bd_f994_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_1/bd_f994_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_1/bd_f994_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_5/bd_f994_s00a2s_0_ooc.xdc

# XDC: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_6/bd_f994_sarn_0_ooc.xdc

# XDC: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_6/bd_f994_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_7/bd_f994_srn_0_ooc.xdc

# XDC: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_7/bd_f994_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_8/bd_f994_m00s2a_0_ooc.xdc

# XDC: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Arty_Z7_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'Arty_Z7_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.srcs/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/Arty_Z7_axi_smc_0.xci
# IP: The module: 'Arty_Z7_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/bd_f994.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_0/bd_f994_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_1/bd_f994_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_2/bd_f994_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_3/bd_f994_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_4/bd_f994_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_5/bd_f994_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_6/bd_f994_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_7/bd_f994_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_8/bd_f994_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_9/bd_f994_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_1/bd_f994_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_1/bd_f994_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_5/bd_f994_s00a2s_0_ooc.xdc

# XDC: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_6/bd_f994_sarn_0_ooc.xdc

# XDC: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_6/bd_f994_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_7/bd_f994_srn_0_ooc.xdc

# XDC: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_7/bd_f994_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/bd_0/ip/ip_8/bd_f994_m00s2a_0_ooc.xdc

# XDC: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Arty_Z7_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'Arty_Z7_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
