/* Generated by Yosys 0.66+2 (git sha1 7d3819c6b, clang++ 18.1.3 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/hyeonseo/mychip/2x2_sa/source/qnn_top_system.v:2.1-66.10" *)
module qnn_top_system(clk, rst_n, start, data_a0, data_a1, wgt_b0, wgt_b1, system_out, o_done);
  (* src = "/home/hyeonseo/mychip/2x2_sa/source/qnn_top_system.v:3.16-3.19" *)
  input clk;
  wire clk;
  (* src = "/home/hyeonseo/mychip/2x2_sa/source/qnn_top_system.v:4.16-4.21" *)
  input rst_n;
  wire rst_n;
  (* src = "/home/hyeonseo/mychip/2x2_sa/source/qnn_top_system.v:5.16-5.21" *)
  input start;
  wire start;
  (* src = "/home/hyeonseo/mychip/2x2_sa/source/qnn_top_system.v:7.22-7.29" *)
  input [3:0] data_a0;
  wire [3:0] data_a0;
  (* src = "/home/hyeonseo/mychip/2x2_sa/source/qnn_top_system.v:8.22-8.29" *)
  input [3:0] data_a1;
  wire [3:0] data_a1;
  (* src = "/home/hyeonseo/mychip/2x2_sa/source/qnn_top_system.v:9.22-9.28" *)
  input [1:0] wgt_b0;
  wire [1:0] wgt_b0;
  (* src = "/home/hyeonseo/mychip/2x2_sa/source/qnn_top_system.v:10.22-10.28" *)
  input [1:0] wgt_b1;
  wire [1:0] wgt_b1;
  (* src = "/home/hyeonseo/mychip/2x2_sa/source/qnn_top_system.v:13.23-13.33" *)
  output [7:0] system_out;
  wire [7:0] system_out;
  (* src = "/home/hyeonseo/mychip/2x2_sa/source/qnn_top_system.v:14.17-14.23" *)
  output o_done;
  wire o_done;
  wire _0_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _10_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _11_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _12_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _13_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _14_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _15_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _16_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _17_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _18_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _19_;
  wire _1_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _20_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _21_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _22_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _23_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _24_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _25_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _26_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _27_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _28_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _29_;
  wire _2_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _30_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _31_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _32_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _33_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _34_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _35_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _36_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _37_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _38_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _39_;
  wire _3_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _40_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  wire _414_;
  wire _415_;
  wire _416_;
  wire _417_;
  wire _418_;
  wire _419_;
  wire _41_;
  wire _420_;
  wire _421_;
  wire _422_;
  wire _423_;
  wire _424_;
  wire _425_;
  wire _426_;
  wire _427_;
  wire _428_;
  wire _429_;
  wire _42_;
  wire _430_;
  wire _431_;
  wire _432_;
  wire _433_;
  wire _434_;
  wire _435_;
  wire _436_;
  wire _437_;
  wire _438_;
  wire _439_;
  wire _43_;
  wire _440_;
  wire _441_;
  wire _442_;
  wire _443_;
  wire _444_;
  wire _445_;
  wire _446_;
  wire _447_;
  wire _448_;
  wire _449_;
  wire _44_;
  wire _450_;
  wire _451_;
  wire _452_;
  wire _453_;
  wire _454_;
  wire _455_;
  wire _456_;
  wire _457_;
  wire _458_;
  wire _459_;
  wire _45_;
  wire _460_;
  wire _461_;
  wire _462_;
  wire _463_;
  wire _464_;
  wire _465_;
  wire _466_;
  wire _467_;
  wire _468_;
  wire _469_;
  wire _46_;
  wire _470_;
  wire _471_;
  wire _472_;
  wire _473_;
  wire _474_;
  wire _475_;
  wire _476_;
  wire _477_;
  wire _478_;
  wire _479_;
  wire _47_;
  wire _480_;
  wire _481_;
  wire _482_;
  wire _483_;
  wire _484_;
  wire _485_;
  wire _486_;
  wire _487_;
  wire _488_;
  wire _489_;
  wire _48_;
  wire _490_;
  wire _491_;
  wire _492_;
  wire _493_;
  wire _494_;
  wire _495_;
  wire _496_;
  wire _497_;
  wire _498_;
  wire _499_;
  wire _49_;
  wire _4_;
  wire _500_;
  wire _501_;
  wire _502_;
  wire _503_;
  wire _504_;
  wire _505_;
  wire _506_;
  (* src = "/home/hyeonseo/mychip/2x2_sa/source/qnn_top_system.v:36.5-48.8" *)
  wire [2:0] _507_;
  wire _508_;
  wire _509_;
  wire _50_;
  wire _510_;
  wire _511_;
  wire _512_;
  wire _513_;
  wire [7:0] _514_;
  wire _515_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  wire _58_;
  wire _59_;
  wire _5_;
  wire _60_;
  wire _61_;
  wire _62_;
  wire _63_;
  wire _64_;
  wire _65_;
  wire _66_;
  wire _67_;
  wire _68_;
  wire _69_;
  wire _6_;
  wire _70_;
  wire _71_;
  wire _72_;
  wire _73_;
  wire _74_;
  wire _75_;
  wire _76_;
  wire _77_;
  wire _78_;
  wire _79_;
  wire _7_;
  wire _80_;
  wire _81_;
  wire _82_;
  wire _83_;
  wire _84_;
  wire _85_;
  wire _86_;
  wire _87_;
  wire _88_;
  wire _89_;
  wire _8_;
  wire _90_;
  wire _91_;
  wire _92_;
  wire _93_;
  wire _94_;
  wire _95_;
  wire _96_;
  wire _97_;
  wire _98_;
  wire _99_;
  wire _9_;
  (* src = "/home/hyeonseo/mychip/2x2_sa/source/qnn_top_system.v:30.10-30.19" *)
  wire clr_accum;
  (* src = "/home/hyeonseo/mychip/2x2_sa/source/qnn_top_system.v:24.16-24.23" *)
  wire [3:0] core_a0;
  (* src = "/home/hyeonseo/mychip/2x2_sa/source/qnn_top_system.v:26.16-26.23" *)
  wire [3:0] core_a1;
  (* src = "/home/hyeonseo/mychip/2x2_sa/source/qnn_top_system.v:25.16-25.23" *)
  wire [1:0] core_b0;
  (* src = "/home/hyeonseo/mychip/2x2_sa/source/qnn_top_system.v:27.16-27.23" *)
  wire [1:0] core_b1;
  (* src = "/home/hyeonseo/mychip/2x2_sa/source/qnn_top_system.v:21.10-21.21" *)
  wire in_a1_valid;
  (* src = "/home/hyeonseo/mychip/2x2_sa/source/qnn_top_system.v:33.16-33.23" *)
  wire [1:0] out_sel;
  (* hdlname = "u_qnn_core a00_to_a01" *)
  (* src = "qnn_systolic_array_2d.v:18.16-18.26" *)
  wire [3:0] \u_qnn_core.a00_to_a01 ;
  (* hdlname = "u_qnn_core a00_to_a01_valid" *)
  (* src = "qnn_systolic_array_2d.v:20.10-20.26" *)
  wire \u_qnn_core.a00_to_a01_valid ;
  (* hdlname = "u_qnn_core a10_to_a11" *)
  (* src = "qnn_systolic_array_2d.v:18.28-18.38" *)
  wire [3:0] \u_qnn_core.a10_to_a11 ;
  (* hdlname = "u_qnn_core a10_to_a11_valid" *)
  (* src = "qnn_systolic_array_2d.v:20.28-20.44" *)
  wire \u_qnn_core.a10_to_a11_valid ;
  (* hdlname = "u_qnn_core b00_to_b10" *)
  (* src = "qnn_systolic_array_2d.v:19.16-19.26" *)
  wire [1:0] \u_qnn_core.b00_to_b10 ;
  (* hdlname = "u_qnn_core b00_to_b10_valid" *)
  (* src = "qnn_systolic_array_2d.v:21.10-21.26" *)
  wire \u_qnn_core.b00_to_b10_valid ;
  (* hdlname = "u_qnn_core b01_to_b11" *)
  (* src = "qnn_systolic_array_2d.v:19.28-19.38" *)
  wire [1:0] \u_qnn_core.b01_to_b11 ;
  (* hdlname = "u_qnn_core b01_to_b11_valid" *)
  (* src = "qnn_systolic_array_2d.v:21.28-21.44" *)
  wire \u_qnn_core.b01_to_b11_valid ;
  (* hdlname = "u_qnn_core pe00 accum_raw" *)
  (* src = "qnn_pe_cell.v:17.16-17.25" *)
  wire [7:0] \u_qnn_core.pe00.accum_raw ;
  (* hdlname = "u_qnn_core pe00 mac_en" *)
  (* src = "qnn_pe_cell.v:18.10-18.16" *)
  wire \u_qnn_core.pe00.mac_en ;
  (* hdlname = "u_qnn_core pe01 accum_raw" *)
  (* src = "qnn_pe_cell.v:17.16-17.25" *)
  wire [7:0] \u_qnn_core.pe01.accum_raw ;
  (* hdlname = "u_qnn_core pe01 mac_en" *)
  (* src = "qnn_pe_cell.v:18.10-18.16" *)
  wire \u_qnn_core.pe01.mac_en ;
  (* hdlname = "u_qnn_core pe10 accum_raw" *)
  (* src = "qnn_pe_cell.v:17.16-17.25" *)
  wire [7:0] \u_qnn_core.pe10.accum_raw ;
  (* hdlname = "u_qnn_core pe10 mac_en" *)
  (* src = "qnn_pe_cell.v:18.10-18.16" *)
  wire \u_qnn_core.pe10.mac_en ;
  (* hdlname = "u_qnn_core pe11 accum_raw" *)
  (* src = "qnn_pe_cell.v:17.16-17.25" *)
  wire [7:0] \u_qnn_core.pe11.accum_raw ;
  (* hdlname = "u_qnn_core pe11 mac_en" *)
  (* src = "qnn_pe_cell.v:18.10-18.16" *)
  wire \u_qnn_core.pe11.mac_en ;
  OAI21X1 _1000_ (
    .A(_376_),
    .B(_361_),
    .C(_358_),
    .Y(_349_)
  );
  INVX1 _1001_ (
    .A(_351_),
    .Y(_350_)
  );
  NAND2X1 _1002_ (
    .A(_376_),
    .B(_361_),
    .Y(_351_)
  );
  OAI21X1 _1003_ (
    .A(_357_),
    .B(_366_),
    .C(_352_),
    .Y(_427_)
  );
  AOI22X1 _1004_ (
    .A(\u_qnn_core.pe11.accum_raw [6]),
    .B(_355_),
    .C(_356_),
    .D(_353_),
    .Y(_352_)
  );
  NOR2X1 _1005_ (
    .A(_354_),
    .B(_359_),
    .Y(_353_)
  );
  INVX1 _1006_ (
    .A(clr_accum),
    .Y(_354_)
  );
  NOR2X1 _1007_ (
    .A(clr_accum),
    .B(\u_qnn_core.pe11.mac_en ),
    .Y(_355_)
  );
  INVX1 _1008_ (
    .A(_372_),
    .Y(_356_)
  );
  OAI21X1 _1009_ (
    .A(_368_),
    .B(_360_),
    .C(_358_),
    .Y(_357_)
  );
  NOR2X1 _1010_ (
    .A(clr_accum),
    .B(_359_),
    .Y(_358_)
  );
  INVX1 _1011_ (
    .A(\u_qnn_core.pe11.mac_en ),
    .Y(_359_)
  );
  OAI21X1 _1012_ (
    .A(_376_),
    .B(_361_),
    .C(_414_),
    .Y(_360_)
  );
  AOI21X1 _1013_ (
    .A(_362_),
    .B(_403_),
    .C(_365_),
    .Y(_361_)
  );
  OAI21X1 _1014_ (
    .A(_396_),
    .B(_363_),
    .C(_394_),
    .Y(_362_)
  );
  AOI21X1 _1015_ (
    .A(_384_),
    .B(_381_),
    .C(_364_),
    .Y(_363_)
  );
  INVX1 _1016_ (
    .A(_389_),
    .Y(_364_)
  );
  INVX1 _1017_ (
    .A(_405_),
    .Y(_365_)
  );
  INVX1 _1018_ (
    .A(_367_),
    .Y(_366_)
  );
  OAI21X1 _1019_ (
    .A(_413_),
    .B(_375_),
    .C(_368_),
    .Y(_367_)
  );
  AND2X2 _1020_ (
    .A(_370_),
    .B(_369_),
    .Y(_368_)
  );
  NAND2X1 _1021_ (
    .A(_374_),
    .B(_372_),
    .Y(_369_)
  );
  INVX1 _1022_ (
    .A(_371_),
    .Y(_370_)
  );
  NOR2X1 _1023_ (
    .A(_374_),
    .B(_372_),
    .Y(_371_)
  );
  NAND2X1 _1024_ (
    .A(\u_qnn_core.b01_to_b11 [1]),
    .B(_373_),
    .Y(_372_)
  );
  NOR2X1 _1025_ (
    .A(_410_),
    .B(_409_),
    .Y(_373_)
  );
  INVX1 _1026_ (
    .A(\u_qnn_core.pe11.accum_raw [6]),
    .Y(_374_)
  );
  AOI21X1 _1027_ (
    .A(_378_),
    .B(_405_),
    .C(_376_),
    .Y(_375_)
  );
  NAND2X1 _1028_ (
    .A(_414_),
    .B(_377_),
    .Y(_376_)
  );
  OR2X2 _1029_ (
    .A(_415_),
    .B(\u_qnn_core.pe11.accum_raw [5]),
    .Y(_377_)
  );
  NAND3X1 _1030_ (
    .A(_402_),
    .B(_395_),
    .C(_379_),
    .Y(_378_)
  );
  NAND3X1 _1031_ (
    .A(_394_),
    .B(_389_),
    .C(_380_),
    .Y(_379_)
  );
  NAND3X1 _1032_ (
    .A(_389_),
    .B(_381_),
    .C(_384_),
    .Y(_380_)
  );
  NAND2X1 _1033_ (
    .A(_383_),
    .B(_382_),
    .Y(_381_)
  );
  OAI21X1 _1034_ (
    .A(\u_qnn_core.b01_to_b11 [1]),
    .B(_411_),
    .C(_392_),
    .Y(_382_)
  );
  INVX1 _1035_ (
    .A(\u_qnn_core.pe11.accum_raw [2]),
    .Y(_383_)
  );
  OAI21X1 _1036_ (
    .A(_386_),
    .B(_385_),
    .C(_388_),
    .Y(_384_)
  );
  AOI21X1 _1037_ (
    .A(_399_),
    .B(_419_),
    .C(\u_qnn_core.pe11.accum_raw [1]),
    .Y(_385_)
  );
  NAND3X1 _1038_ (
    .A(_419_),
    .B(\u_qnn_core.pe11.accum_raw [0]),
    .C(_387_),
    .Y(_386_)
  );
  NOR2X1 _1039_ (
    .A(\u_qnn_core.b01_to_b11 [0]),
    .B(_393_),
    .Y(_387_)
  );
  NAND3X1 _1040_ (
    .A(_419_),
    .B(\u_qnn_core.pe11.accum_raw [1]),
    .C(_399_),
    .Y(_388_)
  );
  NAND3X1 _1041_ (
    .A(\u_qnn_core.pe11.accum_raw [2]),
    .B(_392_),
    .C(_390_),
    .Y(_389_)
  );
  NAND3X1 _1042_ (
    .A(_419_),
    .B(_412_),
    .C(_391_),
    .Y(_390_)
  );
  NAND2X1 _1043_ (
    .A(\u_qnn_core.a10_to_a11 [2]),
    .B(_410_),
    .Y(_391_)
  );
  OAI21X1 _1044_ (
    .A(\u_qnn_core.b01_to_b11 [0]),
    .B(_393_),
    .C(\u_qnn_core.b01_to_b11 [1]),
    .Y(_392_)
  );
  INVX1 _1045_ (
    .A(\u_qnn_core.a10_to_a11 [0]),
    .Y(_393_)
  );
  NAND2X1 _1046_ (
    .A(\u_qnn_core.pe11.accum_raw [3]),
    .B(_397_),
    .Y(_394_)
  );
  INVX1 _1047_ (
    .A(_396_),
    .Y(_395_)
  );
  NOR2X1 _1048_ (
    .A(\u_qnn_core.pe11.accum_raw [3]),
    .B(_397_),
    .Y(_396_)
  );
  OAI21X1 _1049_ (
    .A(\u_qnn_core.b01_to_b11 [1]),
    .B(_416_),
    .C(_398_),
    .Y(_397_)
  );
  NAND2X1 _1050_ (
    .A(\u_qnn_core.b01_to_b11 [1]),
    .B(_399_),
    .Y(_398_)
  );
  OAI21X1 _1051_ (
    .A(\u_qnn_core.b01_to_b11 [0]),
    .B(_401_),
    .C(_400_),
    .Y(_399_)
  );
  NAND2X1 _1052_ (
    .A(\u_qnn_core.b01_to_b11 [0]),
    .B(\u_qnn_core.a10_to_a11 [0]),
    .Y(_400_)
  );
  INVX1 _1053_ (
    .A(\u_qnn_core.a10_to_a11 [1]),
    .Y(_401_)
  );
  AND2X2 _1054_ (
    .A(_405_),
    .B(_403_),
    .Y(_402_)
  );
  NAND2X1 _1055_ (
    .A(_404_),
    .B(_407_),
    .Y(_403_)
  );
  INVX1 _1056_ (
    .A(\u_qnn_core.pe11.accum_raw [4]),
    .Y(_404_)
  );
  NAND2X1 _1057_ (
    .A(\u_qnn_core.pe11.accum_raw [4]),
    .B(_406_),
    .Y(_405_)
  );
  INVX1 _1058_ (
    .A(_407_),
    .Y(_406_)
  );
  OAI21X1 _1059_ (
    .A(_419_),
    .B(_411_),
    .C(_408_),
    .Y(_407_)
  );
  OAI21X1 _1060_ (
    .A(_410_),
    .B(_409_),
    .C(_419_),
    .Y(_408_)
  );
  INVX1 _1061_ (
    .A(\u_qnn_core.a10_to_a11 [3]),
    .Y(_409_)
  );
  INVX1 _1062_ (
    .A(\u_qnn_core.b01_to_b11 [0]),
    .Y(_410_)
  );
  OAI21X1 _1063_ (
    .A(\u_qnn_core.b01_to_b11 [0]),
    .B(_418_),
    .C(_412_),
    .Y(_411_)
  );
  NAND2X1 _1064_ (
    .A(\u_qnn_core.b01_to_b11 [0]),
    .B(\u_qnn_core.a10_to_a11 [1]),
    .Y(_412_)
  );
  INVX1 _1065_ (
    .A(_414_),
    .Y(_413_)
  );
  NAND2X1 _1066_ (
    .A(\u_qnn_core.pe11.accum_raw [5]),
    .B(_415_),
    .Y(_414_)
  );
  NOR2X1 _1067_ (
    .A(_419_),
    .B(_416_),
    .Y(_415_)
  );
  OAI21X1 _1068_ (
    .A(\u_qnn_core.b01_to_b11 [0]),
    .B(\u_qnn_core.a10_to_a11 [3]),
    .C(_417_),
    .Y(_416_)
  );
  NAND2X1 _1069_ (
    .A(\u_qnn_core.b01_to_b11 [0]),
    .B(_418_),
    .Y(_417_)
  );
  INVX1 _1070_ (
    .A(\u_qnn_core.a10_to_a11 [2]),
    .Y(_418_)
  );
  INVX1 _1071_ (
    .A(\u_qnn_core.b01_to_b11 [1]),
    .Y(_419_)
  );
  AND2X2 _1072_ (
    .A(\u_qnn_core.a10_to_a11_valid ),
    .B(\u_qnn_core.b01_to_b11_valid ),
    .Y(\u_qnn_core.pe11.mac_en )
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _1073_ (
    .CLK(clk),
    .D(_457_),
    .Q(\u_qnn_core.pe01.accum_raw [6]),
    .R(rst_n),
    .S(1'h1)
  );
  INVX1 _1074_ (
    .A(out_sel[1]),
    .Y(_482_)
  );
  INVX1 _1075_ (
    .A(_0_),
    .Y(_483_)
  );
  NAND3X1 _1076_ (
    .A(out_sel[0]),
    .B(_482_),
    .C(_483_),
    .Y(_484_)
  );
  INVX1 _1077_ (
    .A(_484_),
    .Y(clr_accum)
  );
  INVX1 _1078_ (
    .A(data_a0[1]),
    .Y(_485_)
  );
  NOR2X1 _1079_ (
    .A(_485_),
    .B(_484_),
    .Y(core_a0[1])
  );
  NAND2X1 _1080_ (
    .A(out_sel[0]),
    .B(_482_),
    .Y(_486_)
  );
  INVX1 _1081_ (
    .A(out_sel[0]),
    .Y(_487_)
  );
  NAND2X1 _1082_ (
    .A(out_sel[1]),
    .B(_487_),
    .Y(_488_)
  );
  NAND2X1 _1083_ (
    .A(_486_),
    .B(_488_),
    .Y(_507_[1])
  );
  NAND3X1 _1084_ (
    .A(out_sel[1]),
    .B(_487_),
    .C(_483_),
    .Y(_489_)
  );
  INVX1 _1085_ (
    .A(_489_),
    .Y(in_a1_valid)
  );
  INVX1 _1086_ (
    .A(wgt_b1[0]),
    .Y(_490_)
  );
  NOR2X1 _1087_ (
    .A(_490_),
    .B(_489_),
    .Y(core_b1[0])
  );
  INVX1 _1088_ (
    .A(start),
    .Y(_491_)
  );
  NOR2X1 _1089_ (
    .A(out_sel[1]),
    .B(_0_),
    .Y(_492_)
  );
  AOI21X1 _1090_ (
    .A(_492_),
    .B(_491_),
    .C(out_sel[0]),
    .Y(_507_[0])
  );
  INVX1 _1091_ (
    .A(data_a1[2]),
    .Y(_493_)
  );
  NOR2X1 _1092_ (
    .A(_493_),
    .B(_489_),
    .Y(core_a1[2])
  );
  INVX1 _1093_ (
    .A(data_a1[1]),
    .Y(_494_)
  );
  NOR2X1 _1094_ (
    .A(_494_),
    .B(_489_),
    .Y(core_a1[1])
  );
  INVX1 _1095_ (
    .A(data_a1[0]),
    .Y(_495_)
  );
  NOR2X1 _1096_ (
    .A(_495_),
    .B(_489_),
    .Y(core_a1[0])
  );
  INVX1 _1097_ (
    .A(wgt_b0[0]),
    .Y(_496_)
  );
  NOR2X1 _1098_ (
    .A(_496_),
    .B(_484_),
    .Y(core_b0[0])
  );
  INVX1 _1099_ (
    .A(data_a0[0]),
    .Y(_497_)
  );
  NOR2X1 _1100_ (
    .A(_497_),
    .B(_484_),
    .Y(core_a0[0])
  );
  INVX1 _1101_ (
    .A(data_a0[2]),
    .Y(_498_)
  );
  NOR2X1 _1102_ (
    .A(_498_),
    .B(_484_),
    .Y(core_a0[2])
  );
  INVX1 _1103_ (
    .A(wgt_b1[1]),
    .Y(_499_)
  );
  NOR2X1 _1104_ (
    .A(_499_),
    .B(_489_),
    .Y(core_b1[1])
  );
  INVX1 _1105_ (
    .A(data_a1[3]),
    .Y(_500_)
  );
  NOR2X1 _1106_ (
    .A(_500_),
    .B(_489_),
    .Y(core_a1[3])
  );
  INVX1 _1107_ (
    .A(wgt_b0[1]),
    .Y(_501_)
  );
  NOR2X1 _1108_ (
    .A(_501_),
    .B(_484_),
    .Y(core_b0[1])
  );
  INVX1 _1109_ (
    .A(data_a0[3]),
    .Y(_502_)
  );
  NOR2X1 _1110_ (
    .A(_502_),
    .B(_484_),
    .Y(core_a0[3])
  );
  NAND3X1 _1111_ (
    .A(out_sel[0]),
    .B(out_sel[1]),
    .C(_483_),
    .Y(_503_)
  );
  OAI21X1 _1112_ (
    .A(_487_),
    .B(_482_),
    .C(_0_),
    .Y(_504_)
  );
  NAND2X1 _1113_ (
    .A(_503_),
    .B(_504_),
    .Y(_507_[2])
  );
  (* src = "/home/hyeonseo/mychip/2x2_sa/source/qnn_top_system.v:36.5-48.8" *)
  DFFSR _1114_ (
    .CLK(clk),
    .D(_507_[2]),
    .Q(_0_),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "/home/hyeonseo/mychip/2x2_sa/source/qnn_top_system.v:36.5-48.8" *)
  DFFSR _1115_ (
    .CLK(clk),
    .D(_507_[0]),
    .Q(out_sel[0]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "/home/hyeonseo/mychip/2x2_sa/source/qnn_top_system.v:36.5-48.8" *)
  DFFSR _1116_ (
    .CLK(clk),
    .D(_507_[1]),
    .Q(out_sel[1]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _1117_ (
    .CLK(clk),
    .D(_29_),
    .Q(\u_qnn_core.pe00.accum_raw [6]),
    .R(rst_n),
    .S(1'h1)
  );
  (* keep = 32'd1 *)
  BUFX2 _516_ (
    .A(_514_[7]),
    .Y(system_out[7])
  );
  (* keep = 32'd1 *)
  BUFX2 _517_ (
    .A(_514_[6]),
    .Y(system_out[6])
  );
  (* keep = 32'd1 *)
  BUFX2 _518_ (
    .A(_514_[5]),
    .Y(system_out[5])
  );
  (* keep = 32'd1 *)
  BUFX2 _519_ (
    .A(_514_[4]),
    .Y(system_out[4])
  );
  (* keep = 32'd1 *)
  BUFX2 _520_ (
    .A(_514_[3]),
    .Y(system_out[3])
  );
  (* keep = 32'd1 *)
  BUFX2 _521_ (
    .A(_514_[2]),
    .Y(system_out[2])
  );
  (* keep = 32'd1 *)
  BUFX2 _522_ (
    .A(_514_[1]),
    .Y(system_out[1])
  );
  (* keep = 32'd1 *)
  BUFX2 _523_ (
    .A(_514_[0]),
    .Y(system_out[0])
  );
  (* keep = 32'd1 *)
  BUFX2 _524_ (
    .A(_0_),
    .Y(o_done)
  );
  NAND2X1 _525_ (
    .A(\u_qnn_core.pe01.accum_raw [2]),
    .B(_277_),
    .Y(_293_)
  );
  NAND2X1 _526_ (
    .A(_289_),
    .B(_292_),
    .Y(_514_[3])
  );
  AND2X2 _527_ (
    .A(_290_),
    .B(_291_),
    .Y(_292_)
  );
  NAND3X1 _528_ (
    .A(out_sel[1]),
    .B(\u_qnn_core.pe10.accum_raw [3]),
    .C(_273_),
    .Y(_291_)
  );
  NAND3X1 _529_ (
    .A(\u_qnn_core.pe00.accum_raw [3]),
    .B(_273_),
    .C(_269_),
    .Y(_290_)
  );
  AND2X2 _530_ (
    .A(_287_),
    .B(_288_),
    .Y(_289_)
  );
  NAND3X1 _531_ (
    .A(out_sel[0]),
    .B(out_sel[1]),
    .C(\u_qnn_core.pe11.accum_raw [3]),
    .Y(_288_)
  );
  NAND3X1 _532_ (
    .A(out_sel[0]),
    .B(\u_qnn_core.pe01.accum_raw [3]),
    .C(_269_),
    .Y(_287_)
  );
  NAND3X1 _533_ (
    .A(_286_),
    .B(_284_),
    .C(_285_),
    .Y(_514_[4])
  );
  AOI22X1 _534_ (
    .A(_282_),
    .B(\u_qnn_core.pe00.accum_raw [4]),
    .C(\u_qnn_core.pe11.accum_raw [4]),
    .D(_281_),
    .Y(_286_)
  );
  NAND2X1 _535_ (
    .A(\u_qnn_core.pe10.accum_raw [4]),
    .B(_279_),
    .Y(_285_)
  );
  NAND2X1 _536_ (
    .A(\u_qnn_core.pe01.accum_raw [4]),
    .B(_277_),
    .Y(_284_)
  );
  NAND3X1 _537_ (
    .A(_283_),
    .B(_278_),
    .C(_280_),
    .Y(_514_[5])
  );
  AOI22X1 _538_ (
    .A(_282_),
    .B(\u_qnn_core.pe00.accum_raw [5]),
    .C(\u_qnn_core.pe11.accum_raw [5]),
    .D(_281_),
    .Y(_283_)
  );
  NOR2X1 _539_ (
    .A(out_sel[0]),
    .B(out_sel[1]),
    .Y(_282_)
  );
  AND2X2 _540_ (
    .A(out_sel[0]),
    .B(out_sel[1]),
    .Y(_281_)
  );
  NAND2X1 _541_ (
    .A(\u_qnn_core.pe10.accum_raw [5]),
    .B(_279_),
    .Y(_280_)
  );
  NOR2X1 _542_ (
    .A(out_sel[0]),
    .B(_269_),
    .Y(_279_)
  );
  NAND2X1 _543_ (
    .A(\u_qnn_core.pe01.accum_raw [5]),
    .B(_277_),
    .Y(_278_)
  );
  NOR2X1 _544_ (
    .A(out_sel[1]),
    .B(_273_),
    .Y(_277_)
  );
  NAND2X1 _545_ (
    .A(_272_),
    .B(_276_),
    .Y(_514_[6])
  );
  AND2X2 _546_ (
    .A(_274_),
    .B(_275_),
    .Y(_276_)
  );
  NAND3X1 _547_ (
    .A(out_sel[1]),
    .B(\u_qnn_core.pe10.accum_raw [6]),
    .C(_273_),
    .Y(_275_)
  );
  NAND3X1 _548_ (
    .A(\u_qnn_core.pe00.accum_raw [6]),
    .B(_273_),
    .C(_269_),
    .Y(_274_)
  );
  INVX1 _549_ (
    .A(out_sel[0]),
    .Y(_273_)
  );
  AND2X2 _550_ (
    .A(_270_),
    .B(_271_),
    .Y(_272_)
  );
  NAND3X1 _551_ (
    .A(out_sel[0]),
    .B(out_sel[1]),
    .C(\u_qnn_core.pe11.accum_raw [6]),
    .Y(_271_)
  );
  NAND3X1 _552_ (
    .A(out_sel[0]),
    .B(\u_qnn_core.pe01.accum_raw [6]),
    .C(_269_),
    .Y(_270_)
  );
  INVX1 _553_ (
    .A(out_sel[1]),
    .Y(_269_)
  );
  NAND2X1 _554_ (
    .A(\u_qnn_core.pe10.accum_raw [2]),
    .B(_279_),
    .Y(_294_)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _555_ (
    .CLK(clk),
    .D(_31_),
    .Q(\u_qnn_core.pe00.accum_raw [7]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _556_ (
    .CLK(clk),
    .D(core_a0[3]),
    .Q(\u_qnn_core.a00_to_a01 [3]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _557_ (
    .CLK(clk),
    .D(core_b0[1]),
    .Q(\u_qnn_core.b00_to_b10 [1]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _558_ (
    .CLK(clk),
    .D(_32_),
    .Q(\u_qnn_core.pe00.accum_raw [4]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _559_ (
    .CLK(clk),
    .D(_33_),
    .Q(\u_qnn_core.pe00.accum_raw [3]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _560_ (
    .CLK(clk),
    .D(clr_accum),
    .Q(\u_qnn_core.a00_to_a01_valid ),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _561_ (
    .CLK(clk),
    .D(_34_),
    .Q(\u_qnn_core.pe00.accum_raw [2]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _562_ (
    .CLK(clk),
    .D(_30_),
    .Q(\u_qnn_core.pe00.accum_raw [5]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _563_ (
    .CLK(clk),
    .D(core_b0[0]),
    .Q(\u_qnn_core.b00_to_b10 [0]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _564_ (
    .CLK(clk),
    .D(clr_accum),
    .Q(\u_qnn_core.b00_to_b10_valid ),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _565_ (
    .CLK(clk),
    .D(_36_),
    .Q(\u_qnn_core.pe00.accum_raw [0]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _566_ (
    .CLK(clk),
    .D(core_a0[0]),
    .Q(\u_qnn_core.a00_to_a01 [0]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _567_ (
    .CLK(clk),
    .D(core_a0[1]),
    .Q(\u_qnn_core.a00_to_a01 [1]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _568_ (
    .CLK(clk),
    .D(core_a0[2]),
    .Q(\u_qnn_core.a00_to_a01 [2]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _569_ (
    .CLK(clk),
    .D(_35_),
    .Q(\u_qnn_core.pe00.accum_raw [1]),
    .R(rst_n),
    .S(1'h1)
  );
  NAND2X1 _570_ (
    .A(_26_),
    .B(_28_),
    .Y(_36_)
  );
  OAI21X1 _571_ (
    .A(clr_accum),
    .B(_24_),
    .C(_27_),
    .Y(_28_)
  );
  NOR2X1 _572_ (
    .A(_475_),
    .B(_23_),
    .Y(_27_)
  );
  OAI21X1 _573_ (
    .A(_475_),
    .B(_23_),
    .C(_25_),
    .Y(_26_)
  );
  NOR2X1 _574_ (
    .A(clr_accum),
    .B(_24_),
    .Y(_25_)
  );
  INVX1 _575_ (
    .A(\u_qnn_core.pe00.accum_raw [0]),
    .Y(_24_)
  );
  NAND2X1 _576_ (
    .A(_37_),
    .B(_69_),
    .Y(_23_)
  );
  OAI21X1 _577_ (
    .A(_17_),
    .B(_19_),
    .C(_22_),
    .Y(_35_)
  );
  AOI22X1 _578_ (
    .A(\u_qnn_core.pe00.accum_raw [1]),
    .B(_479_),
    .C(_21_),
    .D(_481_),
    .Y(_22_)
  );
  INVX1 _579_ (
    .A(_20_),
    .Y(_21_)
  );
  NAND2X1 _580_ (
    .A(_37_),
    .B(_57_),
    .Y(_20_)
  );
  OAI21X1 _581_ (
    .A(_70_),
    .B(_18_),
    .C(_476_),
    .Y(_19_)
  );
  INVX1 _582_ (
    .A(_16_),
    .Y(_18_)
  );
  NOR2X1 _583_ (
    .A(_14_),
    .B(_16_),
    .Y(_17_)
  );
  AND2X2 _584_ (
    .A(_15_),
    .B(_68_),
    .Y(_16_)
  );
  INVX1 _585_ (
    .A(_71_),
    .Y(_15_)
  );
  INVX1 _586_ (
    .A(_70_),
    .Y(_14_)
  );
  OAI21X1 _587_ (
    .A(_10_),
    .B(_11_),
    .C(_13_),
    .Y(_34_)
  );
  AOI22X1 _588_ (
    .A(\u_qnn_core.pe00.accum_raw [2]),
    .B(_479_),
    .C(_12_),
    .D(_481_),
    .Y(_13_)
  );
  INVX1 _589_ (
    .A(_74_),
    .Y(_12_)
  );
  NAND2X1 _590_ (
    .A(_476_),
    .B(_76_),
    .Y(_11_)
  );
  AOI21X1 _591_ (
    .A(_67_),
    .B(_75_),
    .C(_72_),
    .Y(_10_)
  );
  NAND2X1 _592_ (
    .A(_9_),
    .B(_8_),
    .Y(_33_)
  );
  AOI22X1 _593_ (
    .A(\u_qnn_core.pe00.accum_raw [3]),
    .B(_479_),
    .C(_59_),
    .D(_481_),
    .Y(_9_)
  );
  NAND3X1 _594_ (
    .A(_476_),
    .B(_7_),
    .C(_6_),
    .Y(_8_)
  );
  NAND2X1 _595_ (
    .A(_471_),
    .B(_5_),
    .Y(_7_)
  );
  OR2X2 _596_ (
    .A(_5_),
    .B(_471_),
    .Y(_6_)
  );
  NAND2X1 _597_ (
    .A(_62_),
    .B(_61_),
    .Y(_5_)
  );
  OAI21X1 _598_ (
    .A(_2_),
    .B(_3_),
    .C(_4_),
    .Y(_32_)
  );
  AOI22X1 _599_ (
    .A(\u_qnn_core.pe00.accum_raw [4]),
    .B(_479_),
    .C(_50_),
    .D(_481_),
    .Y(_4_)
  );
  NAND2X1 _600_ (
    .A(_476_),
    .B(_78_),
    .Y(_3_)
  );
  NOR2X1 _601_ (
    .A(_54_),
    .B(_472_),
    .Y(_2_)
  );
  NOR2X1 _602_ (
    .A(_513_),
    .B(_1_),
    .Y(_31_)
  );
  OAI21X1 _603_ (
    .A(\u_qnn_core.pe00.accum_raw [7]),
    .B(_515_),
    .C(_480_),
    .Y(_1_)
  );
  AOI21X1 _604_ (
    .A(_467_),
    .B(_464_),
    .C(_475_),
    .Y(_515_)
  );
  NOR3X1 _605_ (
    .A(_475_),
    .B(_511_),
    .C(_512_),
    .Y(_513_)
  );
  AOI21X1 _606_ (
    .A(_474_),
    .B(_465_),
    .C(_463_),
    .Y(_512_)
  );
  INVX1 _607_ (
    .A(\u_qnn_core.pe00.accum_raw [7]),
    .Y(_511_)
  );
  OAI21X1 _608_ (
    .A(_509_),
    .B(_508_),
    .C(_510_),
    .Y(_30_)
  );
  AOI22X1 _609_ (
    .A(\u_qnn_core.pe00.accum_raw [5]),
    .B(_479_),
    .C(_41_),
    .D(_481_),
    .Y(_510_)
  );
  OAI21X1 _610_ (
    .A(_458_),
    .B(_473_),
    .C(_476_),
    .Y(_509_)
  );
  INVX1 _611_ (
    .A(_506_),
    .Y(_508_)
  );
  NAND2X1 _612_ (
    .A(_458_),
    .B(_473_),
    .Y(_506_)
  );
  OAI21X1 _613_ (
    .A(_477_),
    .B(_468_),
    .C(_505_),
    .Y(_29_)
  );
  AOI22X1 _614_ (
    .A(\u_qnn_core.pe00.accum_raw [6]),
    .B(_479_),
    .C(_478_),
    .D(_481_),
    .Y(_505_)
  );
  NOR2X1 _615_ (
    .A(_480_),
    .B(_475_),
    .Y(_481_)
  );
  INVX1 _616_ (
    .A(clr_accum),
    .Y(_480_)
  );
  NOR2X1 _617_ (
    .A(clr_accum),
    .B(\u_qnn_core.pe00.mac_en ),
    .Y(_479_)
  );
  INVX1 _618_ (
    .A(_462_),
    .Y(_478_)
  );
  OAI21X1 _619_ (
    .A(_466_),
    .B(_474_),
    .C(_476_),
    .Y(_477_)
  );
  NOR2X1 _620_ (
    .A(clr_accum),
    .B(_475_),
    .Y(_476_)
  );
  INVX1 _621_ (
    .A(\u_qnn_core.pe00.mac_en ),
    .Y(_475_)
  );
  OAI21X1 _622_ (
    .A(_458_),
    .B(_473_),
    .C(_42_),
    .Y(_474_)
  );
  AOI21X1 _623_ (
    .A(_472_),
    .B(_53_),
    .C(_469_),
    .Y(_473_)
  );
  OAI21X1 _624_ (
    .A(_60_),
    .B(_471_),
    .C(_62_),
    .Y(_472_)
  );
  AOI21X1 _625_ (
    .A(_72_),
    .B(_75_),
    .C(_470_),
    .Y(_471_)
  );
  INVX1 _626_ (
    .A(_67_),
    .Y(_470_)
  );
  INVX1 _627_ (
    .A(_51_),
    .Y(_469_)
  );
  INVX1 _628_ (
    .A(_467_),
    .Y(_468_)
  );
  OAI21X1 _629_ (
    .A(_43_),
    .B(_459_),
    .C(_466_),
    .Y(_467_)
  );
  AND2X2 _630_ (
    .A(_464_),
    .B(_465_),
    .Y(_466_)
  );
  NAND2X1 _631_ (
    .A(_460_),
    .B(_462_),
    .Y(_465_)
  );
  INVX1 _632_ (
    .A(_463_),
    .Y(_464_)
  );
  NOR2X1 _633_ (
    .A(_460_),
    .B(_462_),
    .Y(_463_)
  );
  NAND2X1 _634_ (
    .A(core_b0[1]),
    .B(_461_),
    .Y(_462_)
  );
  NOR2X1 _635_ (
    .A(_46_),
    .B(_47_),
    .Y(_461_)
  );
  INVX1 _636_ (
    .A(\u_qnn_core.pe00.accum_raw [6]),
    .Y(_460_)
  );
  AOI21X1 _637_ (
    .A(_78_),
    .B(_51_),
    .C(_458_),
    .Y(_459_)
  );
  NAND2X1 _638_ (
    .A(_42_),
    .B(_79_),
    .Y(_458_)
  );
  OR2X2 _639_ (
    .A(_41_),
    .B(\u_qnn_core.pe00.accum_raw [5]),
    .Y(_79_)
  );
  NAND3X1 _640_ (
    .A(_54_),
    .B(_61_),
    .C(_77_),
    .Y(_78_)
  );
  NAND3X1 _641_ (
    .A(_62_),
    .B(_67_),
    .C(_76_),
    .Y(_77_)
  );
  NAND3X1 _642_ (
    .A(_67_),
    .B(_75_),
    .C(_72_),
    .Y(_76_)
  );
  NAND2X1 _643_ (
    .A(_73_),
    .B(_74_),
    .Y(_75_)
  );
  OAI21X1 _644_ (
    .A(core_b0[1]),
    .B(_45_),
    .C(_64_),
    .Y(_74_)
  );
  INVX1 _645_ (
    .A(\u_qnn_core.pe00.accum_raw [2]),
    .Y(_73_)
  );
  OAI21X1 _646_ (
    .A(_70_),
    .B(_71_),
    .C(_68_),
    .Y(_72_)
  );
  AOI21X1 _647_ (
    .A(_57_),
    .B(_37_),
    .C(\u_qnn_core.pe00.accum_raw [1]),
    .Y(_71_)
  );
  NAND3X1 _648_ (
    .A(_37_),
    .B(\u_qnn_core.pe00.accum_raw [0]),
    .C(_69_),
    .Y(_70_)
  );
  NOR2X1 _649_ (
    .A(core_b0[0]),
    .B(_63_),
    .Y(_69_)
  );
  NAND3X1 _650_ (
    .A(_37_),
    .B(\u_qnn_core.pe00.accum_raw [1]),
    .C(_57_),
    .Y(_68_)
  );
  NAND3X1 _651_ (
    .A(\u_qnn_core.pe00.accum_raw [2]),
    .B(_64_),
    .C(_66_),
    .Y(_67_)
  );
  NAND3X1 _652_ (
    .A(_37_),
    .B(_44_),
    .C(_65_),
    .Y(_66_)
  );
  NAND2X1 _653_ (
    .A(core_a0[2]),
    .B(_46_),
    .Y(_65_)
  );
  OAI21X1 _654_ (
    .A(core_b0[0]),
    .B(_63_),
    .C(core_b0[1]),
    .Y(_64_)
  );
  INVX1 _655_ (
    .A(core_a0[0]),
    .Y(_63_)
  );
  NAND2X1 _656_ (
    .A(\u_qnn_core.pe00.accum_raw [3]),
    .B(_59_),
    .Y(_62_)
  );
  INVX1 _657_ (
    .A(_60_),
    .Y(_61_)
  );
  NOR2X1 _658_ (
    .A(\u_qnn_core.pe00.accum_raw [3]),
    .B(_59_),
    .Y(_60_)
  );
  OAI21X1 _659_ (
    .A(core_b0[1]),
    .B(_40_),
    .C(_58_),
    .Y(_59_)
  );
  NAND2X1 _660_ (
    .A(core_b0[1]),
    .B(_57_),
    .Y(_58_)
  );
  OAI21X1 _661_ (
    .A(core_b0[0]),
    .B(_55_),
    .C(_56_),
    .Y(_57_)
  );
  NAND2X1 _662_ (
    .A(core_b0[0]),
    .B(core_a0[0]),
    .Y(_56_)
  );
  INVX1 _663_ (
    .A(core_a0[1]),
    .Y(_55_)
  );
  AND2X2 _664_ (
    .A(_51_),
    .B(_53_),
    .Y(_54_)
  );
  NAND2X1 _665_ (
    .A(_52_),
    .B(_49_),
    .Y(_53_)
  );
  INVX1 _666_ (
    .A(\u_qnn_core.pe00.accum_raw [4]),
    .Y(_52_)
  );
  NAND2X1 _667_ (
    .A(\u_qnn_core.pe00.accum_raw [4]),
    .B(_50_),
    .Y(_51_)
  );
  INVX1 _668_ (
    .A(_49_),
    .Y(_50_)
  );
  OAI21X1 _669_ (
    .A(_37_),
    .B(_45_),
    .C(_48_),
    .Y(_49_)
  );
  OAI21X1 _670_ (
    .A(_46_),
    .B(_47_),
    .C(_37_),
    .Y(_48_)
  );
  INVX1 _671_ (
    .A(core_a0[3]),
    .Y(_47_)
  );
  INVX1 _672_ (
    .A(core_b0[0]),
    .Y(_46_)
  );
  OAI21X1 _673_ (
    .A(core_b0[0]),
    .B(_38_),
    .C(_44_),
    .Y(_45_)
  );
  NAND2X1 _674_ (
    .A(core_b0[0]),
    .B(core_a0[1]),
    .Y(_44_)
  );
  INVX1 _675_ (
    .A(_42_),
    .Y(_43_)
  );
  NAND2X1 _676_ (
    .A(\u_qnn_core.pe00.accum_raw [5]),
    .B(_41_),
    .Y(_42_)
  );
  NOR2X1 _677_ (
    .A(_37_),
    .B(_40_),
    .Y(_41_)
  );
  OAI21X1 _678_ (
    .A(core_b0[0]),
    .B(core_a0[3]),
    .C(_39_),
    .Y(_40_)
  );
  NAND2X1 _679_ (
    .A(core_b0[0]),
    .B(_38_),
    .Y(_39_)
  );
  INVX1 _680_ (
    .A(core_a0[2]),
    .Y(_38_)
  );
  INVX1 _681_ (
    .A(core_b0[1]),
    .Y(_37_)
  );
  AND2X2 _682_ (
    .A(clr_accum),
    .B(clr_accum),
    .Y(\u_qnn_core.pe00.mac_en )
  );
  AOI22X1 _683_ (
    .A(_282_),
    .B(\u_qnn_core.pe00.accum_raw [2]),
    .C(\u_qnn_core.pe11.accum_raw [2]),
    .D(_281_),
    .Y(_295_)
  );
  NAND3X1 _684_ (
    .A(_295_),
    .B(_293_),
    .C(_294_),
    .Y(_514_[2])
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _685_ (
    .CLK(clk),
    .D(_455_),
    .Q(\u_qnn_core.pe01.accum_raw [7]),
    .R(rst_n),
    .S(1'h1)
  );
  NAND2X1 _686_ (
    .A(\u_qnn_core.pe01.accum_raw [1]),
    .B(_277_),
    .Y(_296_)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _687_ (
    .CLK(clk),
    .D(core_b1[1]),
    .Q(\u_qnn_core.b01_to_b11 [1]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _688_ (
    .CLK(clk),
    .D(_454_),
    .Q(\u_qnn_core.pe01.accum_raw [4]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _689_ (
    .CLK(clk),
    .D(_453_),
    .Q(\u_qnn_core.pe01.accum_raw [3]),
    .R(rst_n),
    .S(1'h1)
  );
  NAND2X1 _690_ (
    .A(\u_qnn_core.pe10.accum_raw [1]),
    .B(_279_),
    .Y(_297_)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _691_ (
    .CLK(clk),
    .D(_452_),
    .Q(\u_qnn_core.pe01.accum_raw [2]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _692_ (
    .CLK(clk),
    .D(_456_),
    .Q(\u_qnn_core.pe01.accum_raw [5]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _693_ (
    .CLK(clk),
    .D(core_b1[0]),
    .Q(\u_qnn_core.b01_to_b11 [0]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _694_ (
    .CLK(clk),
    .D(in_a1_valid),
    .Q(\u_qnn_core.b01_to_b11_valid ),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _695_ (
    .CLK(clk),
    .D(_450_),
    .Q(\u_qnn_core.pe01.accum_raw [0]),
    .R(rst_n),
    .S(1'h1)
  );
  AOI22X1 _696_ (
    .A(_282_),
    .B(\u_qnn_core.pe00.accum_raw [1]),
    .C(\u_qnn_core.pe11.accum_raw [1]),
    .D(_281_),
    .Y(_298_)
  );
  NAND3X1 _697_ (
    .A(_298_),
    .B(_296_),
    .C(_297_),
    .Y(_514_[1])
  );
  NAND3X1 _698_ (
    .A(out_sel[0]),
    .B(\u_qnn_core.pe01.accum_raw [0]),
    .C(_269_),
    .Y(_299_)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _699_ (
    .CLK(clk),
    .D(_451_),
    .Q(\u_qnn_core.pe01.accum_raw [1]),
    .R(rst_n),
    .S(1'h1)
  );
  NAND2X1 _700_ (
    .A(_82_),
    .B(_80_),
    .Y(_450_)
  );
  OAI21X1 _701_ (
    .A(clr_accum),
    .B(_84_),
    .C(_81_),
    .Y(_80_)
  );
  NOR2X1 _702_ (
    .A(_235_),
    .B(_197_),
    .Y(_81_)
  );
  OAI21X1 _703_ (
    .A(_235_),
    .B(_197_),
    .C(_83_),
    .Y(_82_)
  );
  NOR2X1 _704_ (
    .A(clr_accum),
    .B(_84_),
    .Y(_83_)
  );
  INVX1 _705_ (
    .A(\u_qnn_core.pe01.accum_raw [0]),
    .Y(_84_)
  );
  NAND2X1 _706_ (
    .A(_449_),
    .B(_263_),
    .Y(_197_)
  );
  OAI21X1 _707_ (
    .A(_203_),
    .B(_201_),
    .C(_198_),
    .Y(_451_)
  );
  AOI22X1 _708_ (
    .A(\u_qnn_core.pe01.accum_raw [1]),
    .B(_231_),
    .C(_199_),
    .D(_229_),
    .Y(_198_)
  );
  INVX1 _709_ (
    .A(_200_),
    .Y(_199_)
  );
  NAND2X1 _710_ (
    .A(_449_),
    .B(_429_),
    .Y(_200_)
  );
  OAI21X1 _711_ (
    .A(_262_),
    .B(_202_),
    .C(_234_),
    .Y(_201_)
  );
  INVX1 _712_ (
    .A(_204_),
    .Y(_202_)
  );
  NOR2X1 _713_ (
    .A(_206_),
    .B(_204_),
    .Y(_203_)
  );
  AND2X2 _714_ (
    .A(_205_),
    .B(_264_),
    .Y(_204_)
  );
  INVX1 _715_ (
    .A(_261_),
    .Y(_205_)
  );
  INVX1 _716_ (
    .A(_262_),
    .Y(_206_)
  );
  OAI21X1 _717_ (
    .A(_210_),
    .B(_209_),
    .C(_207_),
    .Y(_452_)
  );
  AOI22X1 _718_ (
    .A(\u_qnn_core.pe01.accum_raw [2]),
    .B(_231_),
    .C(_208_),
    .D(_229_),
    .Y(_207_)
  );
  INVX1 _719_ (
    .A(_258_),
    .Y(_208_)
  );
  NAND2X1 _720_ (
    .A(_234_),
    .B(_256_),
    .Y(_209_)
  );
  AOI21X1 _721_ (
    .A(_265_),
    .B(_257_),
    .C(_260_),
    .Y(_210_)
  );
  NAND2X1 _722_ (
    .A(_211_),
    .B(_212_),
    .Y(_453_)
  );
  AOI22X1 _723_ (
    .A(\u_qnn_core.pe01.accum_raw [3]),
    .B(_231_),
    .C(_315_),
    .D(_229_),
    .Y(_211_)
  );
  NAND3X1 _724_ (
    .A(_234_),
    .B(_213_),
    .C(_214_),
    .Y(_212_)
  );
  NAND2X1 _725_ (
    .A(_239_),
    .B(_215_),
    .Y(_213_)
  );
  OR2X2 _726_ (
    .A(_215_),
    .B(_239_),
    .Y(_214_)
  );
  NAND2X1 _727_ (
    .A(_312_),
    .B(_313_),
    .Y(_215_)
  );
  OAI21X1 _728_ (
    .A(_218_),
    .B(_217_),
    .C(_216_),
    .Y(_454_)
  );
  AOI22X1 _729_ (
    .A(\u_qnn_core.pe01.accum_raw [4]),
    .B(_231_),
    .C(_436_),
    .D(_229_),
    .Y(_216_)
  );
  NAND2X1 _730_ (
    .A(_234_),
    .B(_254_),
    .Y(_217_)
  );
  NOR2X1 _731_ (
    .A(_432_),
    .B(_238_),
    .Y(_218_)
  );
  NOR2X1 _732_ (
    .A(_221_),
    .B(_219_),
    .Y(_455_)
  );
  OAI21X1 _733_ (
    .A(\u_qnn_core.pe01.accum_raw [7]),
    .B(_220_),
    .C(_230_),
    .Y(_219_)
  );
  AOI21X1 _734_ (
    .A(_243_),
    .B(_246_),
    .C(_235_),
    .Y(_220_)
  );
  NOR3X1 _735_ (
    .A(_235_),
    .B(_223_),
    .C(_222_),
    .Y(_221_)
  );
  AOI21X1 _736_ (
    .A(_236_),
    .B(_245_),
    .C(_247_),
    .Y(_222_)
  );
  INVX1 _737_ (
    .A(\u_qnn_core.pe01.accum_raw [7]),
    .Y(_223_)
  );
  OAI21X1 _738_ (
    .A(_225_),
    .B(_226_),
    .C(_224_),
    .Y(_456_)
  );
  AOI22X1 _739_ (
    .A(\u_qnn_core.pe01.accum_raw [5]),
    .B(_231_),
    .C(_445_),
    .D(_229_),
    .Y(_224_)
  );
  OAI21X1 _740_ (
    .A(_252_),
    .B(_237_),
    .C(_234_),
    .Y(_225_)
  );
  INVX1 _741_ (
    .A(_227_),
    .Y(_226_)
  );
  NAND2X1 _742_ (
    .A(_252_),
    .B(_237_),
    .Y(_227_)
  );
  OAI21X1 _743_ (
    .A(_233_),
    .B(_242_),
    .C(_228_),
    .Y(_457_)
  );
  AOI22X1 _744_ (
    .A(\u_qnn_core.pe01.accum_raw [6]),
    .B(_231_),
    .C(_232_),
    .D(_229_),
    .Y(_228_)
  );
  NOR2X1 _745_ (
    .A(_230_),
    .B(_235_),
    .Y(_229_)
  );
  INVX1 _746_ (
    .A(clr_accum),
    .Y(_230_)
  );
  NOR2X1 _747_ (
    .A(clr_accum),
    .B(\u_qnn_core.pe01.mac_en ),
    .Y(_231_)
  );
  INVX1 _748_ (
    .A(_248_),
    .Y(_232_)
  );
  OAI21X1 _749_ (
    .A(_244_),
    .B(_236_),
    .C(_234_),
    .Y(_233_)
  );
  NOR2X1 _750_ (
    .A(clr_accum),
    .B(_235_),
    .Y(_234_)
  );
  INVX1 _751_ (
    .A(\u_qnn_core.pe01.mac_en ),
    .Y(_235_)
  );
  OAI21X1 _752_ (
    .A(_252_),
    .B(_237_),
    .C(_444_),
    .Y(_236_)
  );
  AOI21X1 _753_ (
    .A(_238_),
    .B(_433_),
    .C(_241_),
    .Y(_237_)
  );
  OAI21X1 _754_ (
    .A(_314_),
    .B(_239_),
    .C(_312_),
    .Y(_238_)
  );
  AOI21X1 _755_ (
    .A(_260_),
    .B(_257_),
    .C(_240_),
    .Y(_239_)
  );
  INVX1 _756_ (
    .A(_265_),
    .Y(_240_)
  );
  INVX1 _757_ (
    .A(_435_),
    .Y(_241_)
  );
  INVX1 _758_ (
    .A(_243_),
    .Y(_242_)
  );
  OAI21X1 _759_ (
    .A(_443_),
    .B(_251_),
    .C(_244_),
    .Y(_243_)
  );
  AND2X2 _760_ (
    .A(_246_),
    .B(_245_),
    .Y(_244_)
  );
  NAND2X1 _761_ (
    .A(_250_),
    .B(_248_),
    .Y(_245_)
  );
  INVX1 _762_ (
    .A(_247_),
    .Y(_246_)
  );
  NOR2X1 _763_ (
    .A(_250_),
    .B(_248_),
    .Y(_247_)
  );
  NAND2X1 _764_ (
    .A(core_b1[1]),
    .B(_249_),
    .Y(_248_)
  );
  NOR2X1 _765_ (
    .A(_440_),
    .B(_439_),
    .Y(_249_)
  );
  INVX1 _766_ (
    .A(\u_qnn_core.pe01.accum_raw [6]),
    .Y(_250_)
  );
  AOI21X1 _767_ (
    .A(_254_),
    .B(_435_),
    .C(_252_),
    .Y(_251_)
  );
  NAND2X1 _768_ (
    .A(_444_),
    .B(_253_),
    .Y(_252_)
  );
  OR2X2 _769_ (
    .A(_445_),
    .B(\u_qnn_core.pe01.accum_raw [5]),
    .Y(_253_)
  );
  NAND3X1 _770_ (
    .A(_432_),
    .B(_313_),
    .C(_255_),
    .Y(_254_)
  );
  NAND3X1 _771_ (
    .A(_312_),
    .B(_265_),
    .C(_256_),
    .Y(_255_)
  );
  NAND3X1 _772_ (
    .A(_265_),
    .B(_257_),
    .C(_260_),
    .Y(_256_)
  );
  NAND2X1 _773_ (
    .A(_259_),
    .B(_258_),
    .Y(_257_)
  );
  OAI21X1 _774_ (
    .A(core_b1[1]),
    .B(_441_),
    .C(_268_),
    .Y(_258_)
  );
  INVX1 _775_ (
    .A(\u_qnn_core.pe01.accum_raw [2]),
    .Y(_259_)
  );
  OAI21X1 _776_ (
    .A(_262_),
    .B(_261_),
    .C(_264_),
    .Y(_260_)
  );
  AOI21X1 _777_ (
    .A(_429_),
    .B(_449_),
    .C(\u_qnn_core.pe01.accum_raw [1]),
    .Y(_261_)
  );
  NAND3X1 _778_ (
    .A(_449_),
    .B(\u_qnn_core.pe01.accum_raw [0]),
    .C(_263_),
    .Y(_262_)
  );
  NOR2X1 _779_ (
    .A(core_b1[0]),
    .B(_311_),
    .Y(_263_)
  );
  NAND3X1 _780_ (
    .A(_449_),
    .B(\u_qnn_core.pe01.accum_raw [1]),
    .C(_429_),
    .Y(_264_)
  );
  NAND3X1 _781_ (
    .A(\u_qnn_core.pe01.accum_raw [2]),
    .B(_268_),
    .C(_266_),
    .Y(_265_)
  );
  NAND3X1 _782_ (
    .A(_449_),
    .B(_442_),
    .C(_267_),
    .Y(_266_)
  );
  NAND2X1 _783_ (
    .A(\u_qnn_core.a00_to_a01 [2]),
    .B(_440_),
    .Y(_267_)
  );
  OAI21X1 _784_ (
    .A(core_b1[0]),
    .B(_311_),
    .C(core_b1[1]),
    .Y(_268_)
  );
  INVX1 _785_ (
    .A(\u_qnn_core.a00_to_a01 [0]),
    .Y(_311_)
  );
  NAND2X1 _786_ (
    .A(\u_qnn_core.pe01.accum_raw [3]),
    .B(_315_),
    .Y(_312_)
  );
  INVX1 _787_ (
    .A(_314_),
    .Y(_313_)
  );
  NOR2X1 _788_ (
    .A(\u_qnn_core.pe01.accum_raw [3]),
    .B(_315_),
    .Y(_314_)
  );
  OAI21X1 _789_ (
    .A(core_b1[1]),
    .B(_446_),
    .C(_428_),
    .Y(_315_)
  );
  NAND2X1 _790_ (
    .A(core_b1[1]),
    .B(_429_),
    .Y(_428_)
  );
  OAI21X1 _791_ (
    .A(core_b1[0]),
    .B(_431_),
    .C(_430_),
    .Y(_429_)
  );
  NAND2X1 _792_ (
    .A(core_b1[0]),
    .B(\u_qnn_core.a00_to_a01 [0]),
    .Y(_430_)
  );
  INVX1 _793_ (
    .A(\u_qnn_core.a00_to_a01 [1]),
    .Y(_431_)
  );
  AND2X2 _794_ (
    .A(_435_),
    .B(_433_),
    .Y(_432_)
  );
  NAND2X1 _795_ (
    .A(_434_),
    .B(_437_),
    .Y(_433_)
  );
  INVX1 _796_ (
    .A(\u_qnn_core.pe01.accum_raw [4]),
    .Y(_434_)
  );
  NAND2X1 _797_ (
    .A(\u_qnn_core.pe01.accum_raw [4]),
    .B(_436_),
    .Y(_435_)
  );
  INVX1 _798_ (
    .A(_437_),
    .Y(_436_)
  );
  OAI21X1 _799_ (
    .A(_449_),
    .B(_441_),
    .C(_438_),
    .Y(_437_)
  );
  OAI21X1 _800_ (
    .A(_440_),
    .B(_439_),
    .C(_449_),
    .Y(_438_)
  );
  INVX1 _801_ (
    .A(\u_qnn_core.a00_to_a01 [3]),
    .Y(_439_)
  );
  INVX1 _802_ (
    .A(core_b1[0]),
    .Y(_440_)
  );
  OAI21X1 _803_ (
    .A(core_b1[0]),
    .B(_448_),
    .C(_442_),
    .Y(_441_)
  );
  NAND2X1 _804_ (
    .A(core_b1[0]),
    .B(\u_qnn_core.a00_to_a01 [1]),
    .Y(_442_)
  );
  INVX1 _805_ (
    .A(_444_),
    .Y(_443_)
  );
  NAND2X1 _806_ (
    .A(\u_qnn_core.pe01.accum_raw [5]),
    .B(_445_),
    .Y(_444_)
  );
  NOR2X1 _807_ (
    .A(_449_),
    .B(_446_),
    .Y(_445_)
  );
  OAI21X1 _808_ (
    .A(core_b1[0]),
    .B(\u_qnn_core.a00_to_a01 [3]),
    .C(_447_),
    .Y(_446_)
  );
  NAND2X1 _809_ (
    .A(core_b1[0]),
    .B(_448_),
    .Y(_447_)
  );
  INVX1 _810_ (
    .A(\u_qnn_core.a00_to_a01 [2]),
    .Y(_448_)
  );
  INVX1 _811_ (
    .A(core_b1[1]),
    .Y(_449_)
  );
  AND2X2 _812_ (
    .A(\u_qnn_core.a00_to_a01_valid ),
    .B(in_a1_valid),
    .Y(\u_qnn_core.pe01.mac_en )
  );
  NAND3X1 _813_ (
    .A(out_sel[0]),
    .B(out_sel[1]),
    .C(\u_qnn_core.pe11.accum_raw [0]),
    .Y(_300_)
  );
  AND2X2 _814_ (
    .A(_299_),
    .B(_300_),
    .Y(_301_)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _815_ (
    .CLK(clk),
    .D(_194_),
    .Q(\u_qnn_core.pe10.accum_raw [7]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _816_ (
    .CLK(clk),
    .D(core_a1[3]),
    .Q(\u_qnn_core.a10_to_a11 [3]),
    .R(rst_n),
    .S(1'h1)
  );
  NAND3X1 _817_ (
    .A(\u_qnn_core.pe00.accum_raw [0]),
    .B(_273_),
    .C(_269_),
    .Y(_302_)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _818_ (
    .CLK(clk),
    .D(_193_),
    .Q(\u_qnn_core.pe10.accum_raw [4]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _819_ (
    .CLK(clk),
    .D(_192_),
    .Q(\u_qnn_core.pe10.accum_raw [3]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _820_ (
    .CLK(clk),
    .D(in_a1_valid),
    .Q(\u_qnn_core.a10_to_a11_valid ),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _821_ (
    .CLK(clk),
    .D(_191_),
    .Q(\u_qnn_core.pe10.accum_raw [2]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _822_ (
    .CLK(clk),
    .D(_195_),
    .Q(\u_qnn_core.pe10.accum_raw [5]),
    .R(rst_n),
    .S(1'h1)
  );
  NAND3X1 _823_ (
    .A(out_sel[1]),
    .B(\u_qnn_core.pe10.accum_raw [0]),
    .C(_273_),
    .Y(_303_)
  );
  AND2X2 _824_ (
    .A(_302_),
    .B(_303_),
    .Y(_304_)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _825_ (
    .CLK(clk),
    .D(_189_),
    .Q(\u_qnn_core.pe10.accum_raw [0]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _826_ (
    .CLK(clk),
    .D(core_a1[0]),
    .Q(\u_qnn_core.a10_to_a11 [0]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _827_ (
    .CLK(clk),
    .D(core_a1[1]),
    .Q(\u_qnn_core.a10_to_a11 [1]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _828_ (
    .CLK(clk),
    .D(core_a1[2]),
    .Q(\u_qnn_core.a10_to_a11 [2]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _829_ (
    .CLK(clk),
    .D(_190_),
    .Q(\u_qnn_core.pe10.accum_raw [1]),
    .R(rst_n),
    .S(1'h1)
  );
  NAND2X1 _830_ (
    .A(_87_),
    .B(_85_),
    .Y(_189_)
  );
  OAI21X1 _831_ (
    .A(clr_accum),
    .B(_89_),
    .C(_86_),
    .Y(_85_)
  );
  NOR2X1 _832_ (
    .A(_128_),
    .B(_90_),
    .Y(_86_)
  );
  OAI21X1 _833_ (
    .A(_128_),
    .B(_90_),
    .C(_88_),
    .Y(_87_)
  );
  NOR2X1 _834_ (
    .A(clr_accum),
    .B(_89_),
    .Y(_88_)
  );
  INVX1 _835_ (
    .A(\u_qnn_core.pe10.accum_raw [0]),
    .Y(_89_)
  );
  NAND2X1 _836_ (
    .A(_188_),
    .B(_156_),
    .Y(_90_)
  );
  OAI21X1 _837_ (
    .A(_96_),
    .B(_94_),
    .C(_91_),
    .Y(_190_)
  );
  AOI22X1 _838_ (
    .A(\u_qnn_core.pe10.accum_raw [1]),
    .B(_124_),
    .C(_92_),
    .D(_122_),
    .Y(_91_)
  );
  INVX1 _839_ (
    .A(_93_),
    .Y(_92_)
  );
  NAND2X1 _840_ (
    .A(_188_),
    .B(_168_),
    .Y(_93_)
  );
  OAI21X1 _841_ (
    .A(_155_),
    .B(_95_),
    .C(_127_),
    .Y(_94_)
  );
  INVX1 _842_ (
    .A(_97_),
    .Y(_95_)
  );
  NOR2X1 _843_ (
    .A(_99_),
    .B(_97_),
    .Y(_96_)
  );
  AND2X2 _844_ (
    .A(_98_),
    .B(_157_),
    .Y(_97_)
  );
  INVX1 _845_ (
    .A(_154_),
    .Y(_98_)
  );
  INVX1 _846_ (
    .A(_155_),
    .Y(_99_)
  );
  OAI21X1 _847_ (
    .A(_103_),
    .B(_102_),
    .C(_100_),
    .Y(_191_)
  );
  AOI22X1 _848_ (
    .A(\u_qnn_core.pe10.accum_raw [2]),
    .B(_124_),
    .C(_101_),
    .D(_122_),
    .Y(_100_)
  );
  INVX1 _849_ (
    .A(_151_),
    .Y(_101_)
  );
  NAND2X1 _850_ (
    .A(_127_),
    .B(_149_),
    .Y(_102_)
  );
  AOI21X1 _851_ (
    .A(_158_),
    .B(_150_),
    .C(_153_),
    .Y(_103_)
  );
  NAND2X1 _852_ (
    .A(_104_),
    .B(_105_),
    .Y(_192_)
  );
  AOI22X1 _853_ (
    .A(\u_qnn_core.pe10.accum_raw [3]),
    .B(_124_),
    .C(_166_),
    .D(_122_),
    .Y(_104_)
  );
  NAND3X1 _854_ (
    .A(_127_),
    .B(_106_),
    .C(_107_),
    .Y(_105_)
  );
  NAND2X1 _855_ (
    .A(_132_),
    .B(_108_),
    .Y(_106_)
  );
  OR2X2 _856_ (
    .A(_108_),
    .B(_132_),
    .Y(_107_)
  );
  NAND2X1 _857_ (
    .A(_163_),
    .B(_164_),
    .Y(_108_)
  );
  OAI21X1 _858_ (
    .A(_111_),
    .B(_110_),
    .C(_109_),
    .Y(_193_)
  );
  AOI22X1 _859_ (
    .A(\u_qnn_core.pe10.accum_raw [4]),
    .B(_124_),
    .C(_175_),
    .D(_122_),
    .Y(_109_)
  );
  NAND2X1 _860_ (
    .A(_127_),
    .B(_147_),
    .Y(_110_)
  );
  NOR2X1 _861_ (
    .A(_171_),
    .B(_131_),
    .Y(_111_)
  );
  NOR2X1 _862_ (
    .A(_114_),
    .B(_112_),
    .Y(_194_)
  );
  OAI21X1 _863_ (
    .A(\u_qnn_core.pe10.accum_raw [7]),
    .B(_113_),
    .C(_123_),
    .Y(_112_)
  );
  AOI21X1 _864_ (
    .A(_136_),
    .B(_139_),
    .C(_128_),
    .Y(_113_)
  );
  NOR3X1 _865_ (
    .A(_128_),
    .B(_116_),
    .C(_115_),
    .Y(_114_)
  );
  AOI21X1 _866_ (
    .A(_129_),
    .B(_138_),
    .C(_140_),
    .Y(_115_)
  );
  INVX1 _867_ (
    .A(\u_qnn_core.pe10.accum_raw [7]),
    .Y(_116_)
  );
  OAI21X1 _868_ (
    .A(_118_),
    .B(_119_),
    .C(_117_),
    .Y(_195_)
  );
  AOI22X1 _869_ (
    .A(\u_qnn_core.pe10.accum_raw [5]),
    .B(_124_),
    .C(_184_),
    .D(_122_),
    .Y(_117_)
  );
  OAI21X1 _870_ (
    .A(_145_),
    .B(_130_),
    .C(_127_),
    .Y(_118_)
  );
  INVX1 _871_ (
    .A(_120_),
    .Y(_119_)
  );
  NAND2X1 _872_ (
    .A(_145_),
    .B(_130_),
    .Y(_120_)
  );
  OAI21X1 _873_ (
    .A(_126_),
    .B(_135_),
    .C(_121_),
    .Y(_196_)
  );
  AOI22X1 _874_ (
    .A(\u_qnn_core.pe10.accum_raw [6]),
    .B(_124_),
    .C(_125_),
    .D(_122_),
    .Y(_121_)
  );
  NOR2X1 _875_ (
    .A(_123_),
    .B(_128_),
    .Y(_122_)
  );
  INVX1 _876_ (
    .A(clr_accum),
    .Y(_123_)
  );
  NOR2X1 _877_ (
    .A(clr_accum),
    .B(\u_qnn_core.pe10.mac_en ),
    .Y(_124_)
  );
  INVX1 _878_ (
    .A(_141_),
    .Y(_125_)
  );
  OAI21X1 _879_ (
    .A(_137_),
    .B(_129_),
    .C(_127_),
    .Y(_126_)
  );
  NOR2X1 _880_ (
    .A(clr_accum),
    .B(_128_),
    .Y(_127_)
  );
  INVX1 _881_ (
    .A(\u_qnn_core.pe10.mac_en ),
    .Y(_128_)
  );
  OAI21X1 _882_ (
    .A(_145_),
    .B(_130_),
    .C(_183_),
    .Y(_129_)
  );
  AOI21X1 _883_ (
    .A(_131_),
    .B(_172_),
    .C(_134_),
    .Y(_130_)
  );
  OAI21X1 _884_ (
    .A(_165_),
    .B(_132_),
    .C(_163_),
    .Y(_131_)
  );
  AOI21X1 _885_ (
    .A(_153_),
    .B(_150_),
    .C(_133_),
    .Y(_132_)
  );
  INVX1 _886_ (
    .A(_158_),
    .Y(_133_)
  );
  INVX1 _887_ (
    .A(_174_),
    .Y(_134_)
  );
  INVX1 _888_ (
    .A(_136_),
    .Y(_135_)
  );
  OAI21X1 _889_ (
    .A(_182_),
    .B(_144_),
    .C(_137_),
    .Y(_136_)
  );
  AND2X2 _890_ (
    .A(_139_),
    .B(_138_),
    .Y(_137_)
  );
  NAND2X1 _891_ (
    .A(_143_),
    .B(_141_),
    .Y(_138_)
  );
  INVX1 _892_ (
    .A(_140_),
    .Y(_139_)
  );
  NOR2X1 _893_ (
    .A(_143_),
    .B(_141_),
    .Y(_140_)
  );
  NAND2X1 _894_ (
    .A(\u_qnn_core.b00_to_b10 [1]),
    .B(_142_),
    .Y(_141_)
  );
  NOR2X1 _895_ (
    .A(_179_),
    .B(_178_),
    .Y(_142_)
  );
  INVX1 _896_ (
    .A(\u_qnn_core.pe10.accum_raw [6]),
    .Y(_143_)
  );
  AOI21X1 _897_ (
    .A(_147_),
    .B(_174_),
    .C(_145_),
    .Y(_144_)
  );
  NAND2X1 _898_ (
    .A(_183_),
    .B(_146_),
    .Y(_145_)
  );
  OR2X2 _899_ (
    .A(_184_),
    .B(\u_qnn_core.pe10.accum_raw [5]),
    .Y(_146_)
  );
  NAND3X1 _900_ (
    .A(_171_),
    .B(_164_),
    .C(_148_),
    .Y(_147_)
  );
  NAND3X1 _901_ (
    .A(_163_),
    .B(_158_),
    .C(_149_),
    .Y(_148_)
  );
  NAND3X1 _902_ (
    .A(_158_),
    .B(_150_),
    .C(_153_),
    .Y(_149_)
  );
  NAND2X1 _903_ (
    .A(_152_),
    .B(_151_),
    .Y(_150_)
  );
  OAI21X1 _904_ (
    .A(\u_qnn_core.b00_to_b10 [1]),
    .B(_180_),
    .C(_161_),
    .Y(_151_)
  );
  INVX1 _905_ (
    .A(\u_qnn_core.pe10.accum_raw [2]),
    .Y(_152_)
  );
  OAI21X1 _906_ (
    .A(_155_),
    .B(_154_),
    .C(_157_),
    .Y(_153_)
  );
  AOI21X1 _907_ (
    .A(_168_),
    .B(_188_),
    .C(\u_qnn_core.pe10.accum_raw [1]),
    .Y(_154_)
  );
  NAND3X1 _908_ (
    .A(_188_),
    .B(\u_qnn_core.pe10.accum_raw [0]),
    .C(_156_),
    .Y(_155_)
  );
  NOR2X1 _909_ (
    .A(\u_qnn_core.b00_to_b10 [0]),
    .B(_162_),
    .Y(_156_)
  );
  NAND3X1 _910_ (
    .A(_188_),
    .B(\u_qnn_core.pe10.accum_raw [1]),
    .C(_168_),
    .Y(_157_)
  );
  NAND3X1 _911_ (
    .A(\u_qnn_core.pe10.accum_raw [2]),
    .B(_161_),
    .C(_159_),
    .Y(_158_)
  );
  NAND3X1 _912_ (
    .A(_188_),
    .B(_181_),
    .C(_160_),
    .Y(_159_)
  );
  NAND2X1 _913_ (
    .A(core_a1[2]),
    .B(_179_),
    .Y(_160_)
  );
  OAI21X1 _914_ (
    .A(\u_qnn_core.b00_to_b10 [0]),
    .B(_162_),
    .C(\u_qnn_core.b00_to_b10 [1]),
    .Y(_161_)
  );
  INVX1 _915_ (
    .A(core_a1[0]),
    .Y(_162_)
  );
  NAND2X1 _916_ (
    .A(\u_qnn_core.pe10.accum_raw [3]),
    .B(_166_),
    .Y(_163_)
  );
  INVX1 _917_ (
    .A(_165_),
    .Y(_164_)
  );
  NOR2X1 _918_ (
    .A(\u_qnn_core.pe10.accum_raw [3]),
    .B(_166_),
    .Y(_165_)
  );
  OAI21X1 _919_ (
    .A(\u_qnn_core.b00_to_b10 [1]),
    .B(_185_),
    .C(_167_),
    .Y(_166_)
  );
  NAND2X1 _920_ (
    .A(\u_qnn_core.b00_to_b10 [1]),
    .B(_168_),
    .Y(_167_)
  );
  OAI21X1 _921_ (
    .A(\u_qnn_core.b00_to_b10 [0]),
    .B(_170_),
    .C(_169_),
    .Y(_168_)
  );
  NAND2X1 _922_ (
    .A(\u_qnn_core.b00_to_b10 [0]),
    .B(core_a1[0]),
    .Y(_169_)
  );
  INVX1 _923_ (
    .A(core_a1[1]),
    .Y(_170_)
  );
  AND2X2 _924_ (
    .A(_174_),
    .B(_172_),
    .Y(_171_)
  );
  NAND2X1 _925_ (
    .A(_173_),
    .B(_176_),
    .Y(_172_)
  );
  INVX1 _926_ (
    .A(\u_qnn_core.pe10.accum_raw [4]),
    .Y(_173_)
  );
  NAND2X1 _927_ (
    .A(\u_qnn_core.pe10.accum_raw [4]),
    .B(_175_),
    .Y(_174_)
  );
  INVX1 _928_ (
    .A(_176_),
    .Y(_175_)
  );
  OAI21X1 _929_ (
    .A(_188_),
    .B(_180_),
    .C(_177_),
    .Y(_176_)
  );
  OAI21X1 _930_ (
    .A(_179_),
    .B(_178_),
    .C(_188_),
    .Y(_177_)
  );
  INVX1 _931_ (
    .A(core_a1[3]),
    .Y(_178_)
  );
  INVX1 _932_ (
    .A(\u_qnn_core.b00_to_b10 [0]),
    .Y(_179_)
  );
  OAI21X1 _933_ (
    .A(\u_qnn_core.b00_to_b10 [0]),
    .B(_187_),
    .C(_181_),
    .Y(_180_)
  );
  NAND2X1 _934_ (
    .A(\u_qnn_core.b00_to_b10 [0]),
    .B(core_a1[1]),
    .Y(_181_)
  );
  INVX1 _935_ (
    .A(_183_),
    .Y(_182_)
  );
  NAND2X1 _936_ (
    .A(\u_qnn_core.pe10.accum_raw [5]),
    .B(_184_),
    .Y(_183_)
  );
  NOR2X1 _937_ (
    .A(_188_),
    .B(_185_),
    .Y(_184_)
  );
  OAI21X1 _938_ (
    .A(\u_qnn_core.b00_to_b10 [0]),
    .B(core_a1[3]),
    .C(_186_),
    .Y(_185_)
  );
  NAND2X1 _939_ (
    .A(\u_qnn_core.b00_to_b10 [0]),
    .B(_187_),
    .Y(_186_)
  );
  INVX1 _940_ (
    .A(core_a1[2]),
    .Y(_187_)
  );
  INVX1 _941_ (
    .A(\u_qnn_core.b00_to_b10 [1]),
    .Y(_188_)
  );
  AND2X2 _942_ (
    .A(in_a1_valid),
    .B(\u_qnn_core.b00_to_b10_valid ),
    .Y(\u_qnn_core.pe10.mac_en )
  );
  NAND2X1 _943_ (
    .A(_301_),
    .B(_304_),
    .Y(_514_[0])
  );
  NAND3X1 _944_ (
    .A(out_sel[0]),
    .B(\u_qnn_core.pe01.accum_raw [7]),
    .C(_269_),
    .Y(_305_)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _945_ (
    .CLK(clk),
    .D(_425_),
    .Q(\u_qnn_core.pe11.accum_raw [7]),
    .R(rst_n),
    .S(1'h1)
  );
  NAND3X1 _946_ (
    .A(out_sel[0]),
    .B(out_sel[1]),
    .C(\u_qnn_core.pe11.accum_raw [7]),
    .Y(_306_)
  );
  AND2X2 _947_ (
    .A(_305_),
    .B(_306_),
    .Y(_307_)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _948_ (
    .CLK(clk),
    .D(_424_),
    .Q(\u_qnn_core.pe11.accum_raw [4]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _949_ (
    .CLK(clk),
    .D(_423_),
    .Q(\u_qnn_core.pe11.accum_raw [3]),
    .R(rst_n),
    .S(1'h1)
  );
  NAND3X1 _950_ (
    .A(\u_qnn_core.pe00.accum_raw [7]),
    .B(_273_),
    .C(_269_),
    .Y(_308_)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _951_ (
    .CLK(clk),
    .D(_422_),
    .Q(\u_qnn_core.pe11.accum_raw [2]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _952_ (
    .CLK(clk),
    .D(_426_),
    .Q(\u_qnn_core.pe11.accum_raw [5]),
    .R(rst_n),
    .S(1'h1)
  );
  NAND3X1 _953_ (
    .A(out_sel[1]),
    .B(\u_qnn_core.pe10.accum_raw [7]),
    .C(_273_),
    .Y(_309_)
  );
  AND2X2 _954_ (
    .A(_308_),
    .B(_309_),
    .Y(_310_)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _955_ (
    .CLK(clk),
    .D(_420_),
    .Q(\u_qnn_core.pe11.accum_raw [0]),
    .R(rst_n),
    .S(1'h1)
  );
  NAND2X1 _956_ (
    .A(_307_),
    .B(_310_),
    .Y(_514_[7])
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _957_ (
    .CLK(clk),
    .D(_427_),
    .Q(\u_qnn_core.pe11.accum_raw [6]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _958_ (
    .CLK(clk),
    .D(_196_),
    .Q(\u_qnn_core.pe10.accum_raw [6]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "qnn_mac_pe.v:28.5-46.8" *)
  DFFSR _959_ (
    .CLK(clk),
    .D(_421_),
    .Q(\u_qnn_core.pe11.accum_raw [1]),
    .R(rst_n),
    .S(1'h1)
  );
  NAND2X1 _960_ (
    .A(_318_),
    .B(_316_),
    .Y(_420_)
  );
  OAI21X1 _961_ (
    .A(clr_accum),
    .B(_320_),
    .C(_317_),
    .Y(_316_)
  );
  NOR2X1 _962_ (
    .A(_359_),
    .B(_321_),
    .Y(_317_)
  );
  OAI21X1 _963_ (
    .A(_359_),
    .B(_321_),
    .C(_319_),
    .Y(_318_)
  );
  NOR2X1 _964_ (
    .A(clr_accum),
    .B(_320_),
    .Y(_319_)
  );
  INVX1 _965_ (
    .A(\u_qnn_core.pe11.accum_raw [0]),
    .Y(_320_)
  );
  NAND2X1 _966_ (
    .A(_419_),
    .B(_387_),
    .Y(_321_)
  );
  OAI21X1 _967_ (
    .A(_327_),
    .B(_325_),
    .C(_322_),
    .Y(_421_)
  );
  AOI22X1 _968_ (
    .A(\u_qnn_core.pe11.accum_raw [1]),
    .B(_355_),
    .C(_323_),
    .D(_353_),
    .Y(_322_)
  );
  INVX1 _969_ (
    .A(_324_),
    .Y(_323_)
  );
  NAND2X1 _970_ (
    .A(_419_),
    .B(_399_),
    .Y(_324_)
  );
  OAI21X1 _971_ (
    .A(_386_),
    .B(_326_),
    .C(_358_),
    .Y(_325_)
  );
  INVX1 _972_ (
    .A(_328_),
    .Y(_326_)
  );
  NOR2X1 _973_ (
    .A(_330_),
    .B(_328_),
    .Y(_327_)
  );
  AND2X2 _974_ (
    .A(_329_),
    .B(_388_),
    .Y(_328_)
  );
  INVX1 _975_ (
    .A(_385_),
    .Y(_329_)
  );
  INVX1 _976_ (
    .A(_386_),
    .Y(_330_)
  );
  OAI21X1 _977_ (
    .A(_334_),
    .B(_333_),
    .C(_331_),
    .Y(_422_)
  );
  AOI22X1 _978_ (
    .A(\u_qnn_core.pe11.accum_raw [2]),
    .B(_355_),
    .C(_332_),
    .D(_353_),
    .Y(_331_)
  );
  INVX1 _979_ (
    .A(_382_),
    .Y(_332_)
  );
  NAND2X1 _980_ (
    .A(_358_),
    .B(_380_),
    .Y(_333_)
  );
  AOI21X1 _981_ (
    .A(_389_),
    .B(_381_),
    .C(_384_),
    .Y(_334_)
  );
  NAND2X1 _982_ (
    .A(_335_),
    .B(_336_),
    .Y(_423_)
  );
  AOI22X1 _983_ (
    .A(\u_qnn_core.pe11.accum_raw [3]),
    .B(_355_),
    .C(_397_),
    .D(_353_),
    .Y(_335_)
  );
  NAND3X1 _984_ (
    .A(_358_),
    .B(_337_),
    .C(_338_),
    .Y(_336_)
  );
  NAND2X1 _985_ (
    .A(_363_),
    .B(_339_),
    .Y(_337_)
  );
  OR2X2 _986_ (
    .A(_339_),
    .B(_363_),
    .Y(_338_)
  );
  NAND2X1 _987_ (
    .A(_394_),
    .B(_395_),
    .Y(_339_)
  );
  OAI21X1 _988_ (
    .A(_342_),
    .B(_341_),
    .C(_340_),
    .Y(_424_)
  );
  AOI22X1 _989_ (
    .A(\u_qnn_core.pe11.accum_raw [4]),
    .B(_355_),
    .C(_406_),
    .D(_353_),
    .Y(_340_)
  );
  NAND2X1 _990_ (
    .A(_358_),
    .B(_378_),
    .Y(_341_)
  );
  NOR2X1 _991_ (
    .A(_402_),
    .B(_362_),
    .Y(_342_)
  );
  NOR2X1 _992_ (
    .A(_345_),
    .B(_343_),
    .Y(_425_)
  );
  OAI21X1 _993_ (
    .A(\u_qnn_core.pe11.accum_raw [7]),
    .B(_344_),
    .C(_354_),
    .Y(_343_)
  );
  AOI21X1 _994_ (
    .A(_367_),
    .B(_370_),
    .C(_359_),
    .Y(_344_)
  );
  NOR3X1 _995_ (
    .A(_359_),
    .B(_347_),
    .C(_346_),
    .Y(_345_)
  );
  AOI21X1 _996_ (
    .A(_360_),
    .B(_369_),
    .C(_371_),
    .Y(_346_)
  );
  INVX1 _997_ (
    .A(\u_qnn_core.pe11.accum_raw [7]),
    .Y(_347_)
  );
  OAI21X1 _998_ (
    .A(_349_),
    .B(_350_),
    .C(_348_),
    .Y(_426_)
  );
  AOI22X1 _999_ (
    .A(\u_qnn_core.pe11.accum_raw [5]),
    .B(_355_),
    .C(_415_),
    .D(_353_),
    .Y(_348_)
  );
endmodule
