# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.srcs/sources_1/bd/Arty_Z7/ip/Arty_Z7_proc_sys_reset_0_0/Arty_Z7_proc_sys_reset_0_0.xci
# IP: The module: 'Arty_Z7_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_proc_sys_reset_0_0/Arty_Z7_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Arty_Z7_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_proc_sys_reset_0_0/Arty_Z7_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Arty_Z7_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_proc_sys_reset_0_0/Arty_Z7_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Arty_Z7_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.srcs/sources_1/bd/Arty_Z7/ip/Arty_Z7_proc_sys_reset_0_0/Arty_Z7_proc_sys_reset_0_0.xci
# IP: The module: 'Arty_Z7_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_proc_sys_reset_0_0/Arty_Z7_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Arty_Z7_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_proc_sys_reset_0_0/Arty_Z7_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Arty_Z7_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/NPU_project/CNN-Handwritten-Digit-MNIST-main/CNN-Handwritten-Digit-MNIST-main/Network/Vivado/CNN-MNIST-Arty-Z7/CNN-MNIST-Arty-Z7.gen/sources_1/bd/Arty_Z7/ip/Arty_Z7_proc_sys_reset_0_0/Arty_Z7_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Arty_Z7_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
